on: 
 push:
   branches:
      - main
permissions: write-all
name: Release

jobs:
  step1:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - run: go mod tidy
    - run: go build -o ./artifacts/gogetit-${{ matrix.os }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
       name: artifacts
       path: artifacts
       
  step2:
   needs: step1
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts
          path: artifacts
          
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
         draft: false
         prerelease: false
         release_name: ${{ steps.version.outputs.version }}
         tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
